新功能：任務可以被貼標籤
jimmy2822/iMission pull request #11
Opened 2018-11-26 16:01 UTC by jimmy2822

任務現在可以被貼標籤，並在任務列表顯示任務擁有的標籤

2018-11-26 16:39 UTC, elct9620 approved these changes

2018-11-26 16:39 UTC, elct9620 commented on app/controllers/tasks_controller.rb
> +    @task.tag_list=(params[:tags])
你可以考慮：

1. `task_params[:tags]`
2. 把 `tags` 改名為 `tag_list` 讓你在 `Tas.new(task_params)` 就吃到

2018-11-30 16:27 UTC, elct9620 requested changes

2018-12-01 09:44 UTC, jimmy2822 commented on spec/rails_helper.rb
> +# Capybara.register_driver :selenium do |app|
已刪除XD

2018-12-01 10:11 UTC, merged